import './globals.css'

export const metadata = {
  title: 'E-Commerce App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='bg-gray-100 w-full max-h-full h-screen'>{children}</body>
    </html>
  )
}
